name: 'Prepare Server Test Environment'
description: 'Prepare Server Test Environment'

runs:
  using: 'composite'
  steps:
    - name: Initialize database
      shell: bash
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE polymind;"
        psql -h localhost -U postgres -c "CREATE USER polymind WITH PASSWORD 'polymind';"
        psql -h localhost -U postgres -c "ALTER USER polymind WITH SUPERUSER;"
      env:
        PGPASSWORD: polymind

    - name: Run init-db script
      shell: bash
      env:
        NODE_ENV: test
      run: |
        yarn polymind @polymind/server prisma generate
        yarn polymind @polymind/server prisma migrate deploy
        yarn polymind @polymind/server data-migration run

    - name: Import config
      shell: bash
      env:
        DEFAULT_CONFIG: '{}'
      run: |
        printf '%s\n' "${SERVER_CONFIG:-$DEFAULT_CONFIG}" > ./packages/backend/server/config.json
